### ISSUE TITLE
Wondering

### ISSUE THREAD

**Issue by clumsyzombie** [kennethrisa/Stats#21]
I was wondering why am I only getting stats_player and Stats_player_death from my Server into my DB. I was using the SQLStats.cs that was provided in the zip file and for some reason I feel like I am not getting all the details I should be as I have 8 days or more running this and I am not getting any info inserted into the DB but the 2 tables. 

![capture1234](https://user-images.githubusercontent.com/15150210/27868922-dcc10eb4-6163-11e7-8092-d01fd4aa038a.PNG)

**Comment by kennethrisa** [comment]
Updated the plugin, SQLStats.cs with the missing features who i deleted a long time ago beacuse of peformance issues.

I have now added them back, but not  stats_player_place_deployable and player_place_building.
