### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jaysimo** [kennethrisa/Stats#25]
so when after setting everything up and visiting http://localhost i get a error page from nginx nothing else any idea why? thanks

**Comment by jaysimo** [comment]
An error occurred.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, nginx.

**Comment by jaysimo** [comment]
2018/11/06 20:15:19 [error] 4324#4344: *5 CreateFile() "C:\nginx/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2018/11/06 20:18:26 [error] 4324#4344: *8 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1"
2018/11/06 20:18:26 [error] 4324#4344: *8 CreateFile() "C:\nginx/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2018/11/06 20:33:50 [error] 4324#4344: *11 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1"

**Comment by kennethrisa** [comment]
This is not an issue - php process is not running. closing issue
